awhomecategories_form_configuration:
  path: /awhomecategories/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'Axelweb\AwHomeCategories\Controller\AdminConfigurationController::index'
    # Needed to work with tab system
    _legacy_controller: AdminAwHomeCategories
    _legacy_link: AdminAwHomeCategories
